### ISSUE TITLE
Error installing mod from webgui

### ISSUE THREAD

**Issue by rogueops** [xtr4nge/module_stalker#1]
just never installs

Log shows
#4 /usr/share/fruitywifi/www/modules/fruityproxy/includes/ws.php(72): Requests_Session->get('http:/" while reading response header from upstream, client: 192.168.1.108, server: , request: "GET /modules/fruityproxy/includes/ws_action.php?method=getModulesStatusAll HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-8000.sock:", host: "172.21.42.102:8000", referrer: "http://172.21.42.102:8000/page_status.php"
#3 /usr/share/fruitywifi/www/modules/fruityproxy/includes/Requests/Requests/Session.php(132):
#2 /usr/share/fruitywifi/www/modules/fruityproxy/includes/Requests/Requests/Session.php(205): Requests::request('http://127.0.0....', Array, NULL, 'GET', Array)
#1 /usr/share/fruitywifi/www/modules/fruityproxy/includes/Requests/Requests.php(325): Requests_Transport_cURL->request('http://127.0.0....', Array, NULL, Array)
#0 /usr/share/fruitywifi/www/modules/fruityproxy/includes/Requests/Requests/Transport/cURL.php(126): Requests_Transport_cURL->process_response(false, Array)

Stack trace:
2015/10/30 01:12:24 [error] 594#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Requests_Exception' with message 'cURL error 7: Failed to connect to 127.0.0.1 port 8081: Connection refused' in /usr/share/fruitywifi/www/modules/fruityproxy/includes/Requests/Requests/Transport/cURL.php:291

**Comment by xtr4nge** [comment]
Hi gh0stshell,
You can download the modules manually and you can exec the installation script manually, but it will be better if you fix the root issue with the setup/installation.

This is a topic for the forum. Please open a new thread in:
http://fruitywifi.boards.net/

regards,

**Comment by rogueops** [comment]
When I try that via your FAQ I have no install for the modules that are listed as install.
